<?xml version="1.0" encoding="UTF-8" ?>
<!--ITK-SNAP (itksnap.org) Project File

This file can be moved/copied along with the images that it references
as long as the relative location of the images to the project file is 
the same. Do not modify the SaveLocation entry, or this will not work.
-->
<!DOCTYPE registry [
<!ELEMENT registry (entry*,folder*)>
<!ELEMENT folder (entry*,folder*)>
<!ELEMENT entry EMPTY>
<!ATTLIST folder key CDATA #REQUIRED>
<!ATTLIST entry key CDATA #REQUIRED>
<!ATTLIST entry value CDATA #REQUIRED>
]>
<registry>
  <entry key="SaveLocation" value="PROJECT_ROOT" />
  <entry key="Version" value="20240422" />
  <folder key="Annotations" >
    <entry key="Format" value="ITK-SNAP Annotation File" />
    <entry key="FormatDate" value="20150624" />
  </folder>
  <folder key="Layers" >
    <folder key="Layer[000]" >
      <entry key="AbsolutePath" value="TARGET_T1_PATH" />
      <entry key="Role" value="MainRole" />
      <entry key="Tags" value="" />
      <folder key="IOHints" >
        <entry key="Format" value="NiFTI" />
      </folder>
      <folder key="LayerMetaData" >
        <entry key="Alpha" value="255" />
        <entry key="CustomNickName" value="T1_MNI" />
        <entry key="Sticky" value="0" />
        <entry key="Tags" value="" />
        <folder key="DisplayMapping" >
          <folder key="ColorMap" >
            <entry key="Preset" value="Grayscale" />
          </folder>
          <folder key="Curve" >
            <entry key="NumberOfControlPoints" value="3" />
            <folder key="ControlPoint[0]" >
              <entry key="tValue" value="0" />
              <entry key="xValue" value="0" />
            </folder>
            <folder key="ControlPoint[1]" >
              <entry key="tValue" value="0.5" />
              <entry key="xValue" value="0.5" />
            </folder>
            <folder key="ControlPoint[2]" >
              <entry key="tValue" value="1" />
              <entry key="xValue" value="1" />
            </folder>
          </folder>
        </folder>
      </folder>
      <folder key="ProjectMetaData" >
        <entry key="GaussianBlurScale" value="1" />
        <entry key="RemappingExponent" value="3" />
        <entry key="RemappingSteepness" value="0.04" />
        <folder key="Files" >
        </folder>
        <folder key="IOHistory" >
          <folder key="AnatomicImage" >
            <entry key="ArraySize" value="1" />
            <entry key="Element[0]" value="TARGET_NM_PATH" />
          </folder>
        </folder>
        <folder key="IRIS" >
          <entry key="SliceViewLayerLayout" value="Stacked" />
          <folder key="DisplayMapping" >
            <folder key="ColorMap" >
              <entry key="Preset" value="Grayscale" />
            </folder>
            <folder key="Curve" >
              <entry key="NumberOfControlPoints" value="3" />
              <folder key="ControlPoint[0]" >
                <entry key="tValue" value="0" />
                <entry key="xValue" value="0" />
              </folder>
              <folder key="ControlPoint[1]" >
                <entry key="tValue" value="0.5" />
                <entry key="xValue" value="0.5" />
              </folder>
              <folder key="ControlPoint[2]" >
                <entry key="tValue" value="1" />
                <entry key="xValue" value="1" />
              </folder>
            </folder>
          </folder>
          <folder key="LabelState" >
            <entry key="CoverageMode" value="OverAll" />
            <entry key="DrawingLabel" value="1" />
            <entry key="OverwriteLabel" value="0" />
            <entry key="PolygonInvert" value="0" />
            <entry key="SegmentationAlpha" value="0.5" />
          </folder>
          <folder key="LabelTable" >
            <entry key="NumberOfElements" value="6" />
            <folder key="Element[0]" >
              <entry key="Alpha" value="255" />
              <entry key="Color" value="255 0 0" />
              <entry key="Flags" value="1 1" />
              <entry key="Index" value="1" />
              <entry key="Label" value="Cerebral Penducle (Background)" />
            </folder>
            <folder key="Element[1]" >
              <entry key="Alpha" value="255" />
              <entry key="Color" value="0 255 0" />
              <entry key="Flags" value="1 1" />
              <entry key="Index" value="2" />
              <entry key="Label" value="Substantia Nigra (Target)" />
            </folder>
          </folder>
          <folder key="MeshOptions" >
            <entry key="DecimateFeatureAngle" value="45" />
            <entry key="DecimateMaximumError" value="0.002" />
            <entry key="DecimatePreserveTopology" value="1" />
            <entry key="DecimateTargetReduction" value="0.95" />
            <entry key="GaussianError" value="0.03" />
            <entry key="GaussianStandardDeviation" value="0.8" />
            <entry key="MeshSmoothingBoundarySmoothing" value="0" />
            <entry key="MeshSmoothingConvergence" value="0" />
            <entry key="MeshSmoothingFeatureAngle" value="45" />
            <entry key="MeshSmoothingFeatureEdgeSmoothing" value="0" />
            <entry key="MeshSmoothingIterations" value="20" />
            <entry key="MeshSmoothingRelaxationFactor" value="0.01" />
            <entry key="UseDecimation" value="0" />
            <entry key="UseGaussianSmoothing" value="1" />
            <entry key="UseMeshSmoothing" value="0" />
          </folder>
        </folder>
        <folder key="SNAP" >
          <folder key="SnakeParameters" >
            <entry key="AdvectionSpeedExponent" value="0" />
            <entry key="AdvectionWeight" value="0" />
            <entry key="AutomaticTimeStep" value="1" />
            <entry key="Clamp" value="1" />
            <entry key="CurvatureSpeedExponent" value="-1" />
            <entry key="CurvatureWeight" value="0.2" />
            <entry key="Ground" value="5" />
            <entry key="LaplacianSpeedExponent" value="0" />
            <entry key="LaplacianWeight" value="0" />
            <entry key="PropagationSpeedExponent" value="1" />
            <entry key="PropagationWeight" value="1" />
            <entry key="SnakeType" value="RegionCompetition" />
            <entry key="SolverAlgorithm" value="ParallelSparseField" />
            <entry key="TimeStepFactor" value="1" />
          </folder>
        </folder>
      </folder>
    </folder>
    <folder key="Layer[001]" >
      <entry key="AbsolutePath" value="TARGET_NM_PATH" />
      <entry key="Role" value="OverlayRole" />
      <entry key="Tags" value="" />
      <folder key="IOHints" >
        <entry key="Format" value="NiFTI" />
      </folder>
      <folder key="ImageTransform" >
        <entry key="IsIdentity" value="1" />
      </folder>
      <folder key="LayerMetaData" >
        <entry key="Alpha" value="0.78" />
        <entry key="CustomNickName" value="Subject_Average_NM" />
        <entry key="Sticky" value="1" />
        <entry key="Tags" value="" />
        <folder key="DisplayMapping" >
          <folder key="ColorMap" >
            <entry key="NumberOfControlPoints" value="3" />
            <entry key="Preset" value="Custom" />
            <folder key="ControlPoint[0000]" >
              <entry key="Index" value="0" />
              <entry key="Type" value="Discontinuous" />
              <folder key="Left" >
                <entry key="A" value="0" />
                <entry key="B" value="255" />
                <entry key="G" value="0" />
                <entry key="R" value="0" />
              </folder>
              <folder key="Right" >
                <entry key="A" value="255" />
                <entry key="B" value="255" />
                <entry key="G" value="0" />
                <entry key="R" value="0" />
              </folder>
            </folder>
            <folder key="ControlPoint[0001]" >
              <entry key="Index" value="0.8334" />
              <entry key="Type" value="Continuous" />
              <folder key="Left" >
                <entry key="A" value="255" />
                <entry key="B" value="106" />
                <entry key="G" value="170" />
                <entry key="R" value="255" />
              </folder>
              <folder key="Right" >
                <entry key="A" value="255" />
                <entry key="B" value="106" />
                <entry key="G" value="170" />
                <entry key="R" value="255" />
              </folder>
            </folder>
            <folder key="ControlPoint[0002]" >
              <entry key="Index" value="1" />
              <entry key="Type" value="Discontinuous" />
              <folder key="Left" >
                <entry key="A" value="255" />
                <entry key="B" value="128" />
                <entry key="G" value="204" />
                <entry key="R" value="255" />
              </folder>
              <folder key="Right" >
                <entry key="A" value="255" />
                <entry key="B" value="128" />
                <entry key="G" value="204" />
                <entry key="R" value="255" />
              </folder>
            </folder>
            <folder key="NaNColor" >
              <entry key="A" value="255" />
              <entry key="B" value="255" />
              <entry key="G" value="255" />
              <entry key="R" value="255" />
            </folder>
          </folder>
          <folder key="Curve" >
            <entry key="NumberOfControlPoints" value="3" />
            <folder key="ControlPoint[0]" >
              <entry key="tValue" value="-0.050625" />
              <entry key="xValue" value="0" />
            </folder>
            <folder key="ControlPoint[1]" >
              <entry key="tValue" value="0.348149" />
              <entry key="xValue" value="0.317021" />
            </folder>
            <folder key="ControlPoint[2]" >
              <entry key="tValue" value="0.692074" />
              <entry key="xValue" value="1" />
            </folder>
          </folder>
        </folder>
      </folder>
    </folder>
  </folder>
  <folder key="TimePointProperties" >
    <entry key="FormatVersion" value="1" />
    <folder key="TimePoints" >
      <entry key="ArraySize" value="1" />
      <folder key="TimePoint[1]" >
        <entry key="Nickname" value="" />
        <entry key="Tags" value="" />
        <entry key="TimePoint" value="1" />
      </folder>
    </folder>
  </folder>
 <folder key="Segmentation" >
   <entry key="AbsolutePath" value="TARGET_MASK_PATH" />
 </folder>
</registry>
